const trainSchedules = [
  // March 12, 2025 - Multiple time slots
  {
    trainNumber: "LI1-1",
    route: "Lagos - Ibadan",
    timeOfDay: "Morning Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "07:03",
      date: "12 - Mar - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "08:45",
      date: "12 - Mar - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 12,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 9,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 7,
      },
    ],
  },
  {
    trainNumber: "LI1-2",
    route: "Lagos - Ibadan",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "13:03",
      date: "12 - Mar - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "14:45",
      date: "12 - Mar - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 7,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 12,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 15,
      },
    ],
  },
  {
    trainNumber: "LI1-3",
    route: "Lagos - Ibadan",
    timeOfDay: "Evening Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "16:03",
      date: "12 - Mar - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "17:45",
      date: "12 - Mar - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 5,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 18,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 9,
      },
    ],
  },

  // March 23, 2025 - Multiple time slots
  {
    trainNumber: "LI1-4",
    route: "Lagos - Ibadan",
    timeOfDay: "Morning Train",
    departure: {
      station: "Babatunde Raji Fashola Station",
      street: "Agege",
      year: "2025",
      time: "07:03",
      date: "23 - Mar - 2025",
    },
    arrival: {
      station: "Lateef Kayode Jakande Station",
      street: "Agbado",
      year: "2025",
      time: "08:45",
      date: "23 - Mar - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 10,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 15,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 8,
      },
    ],
  },
  {
    trainNumber: "LI1-5",
    route: "Lagos - Ibadan",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Babatunde Raji Fashola Station",
      street: "Agege",
      year: "2025",
      time: "13:03",
      date: "23 - Mar - 2025",
    },
    arrival: {
      station: "Lateef Kayode Jakande Station",
      street: "Agbado",
      year: "2025",
      time: "14:45",
      date: "23 - Mar - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 18,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 6,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 10,
      },
    ],
  },

  // March 5, 2025 - Multiple time slots
  {
    trainNumber: "IL2-1",
    route: "Ibadan - Lagos",
    timeOfDay: "Morning Train",
    departure: {
      station: "Obafemi Awolowo Station",
      street: "Moniya",
      year: "2025",
      time: "07:03",
      date: "05 - Mar - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "08:45",
      date: "05 - Mar - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 8,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 14,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 9,
      },
    ],
  },
  {
    trainNumber: "IL2-2",
    route: "Ibadan - Lagos",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Obafemi Awolowo Station",
      street: "Moniya",
      year: "2025",
      time: "11:03",
      date: "05 - Mar - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "12:45",
      date: "05 - Mar - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 18,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 7,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 11,
      },
    ],
  },
  {
    trainNumber: "IL2-3",
    route: "Ibadan - Lagos",
    timeOfDay: "Evening Train",
    departure: {
      station: "Obafemi Awolowo Station",
      street: "Moniya",
      year: "2025",
      time: "16:03",
      date: "05 - Mar - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "17:45",
      date: "05 - Mar - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 14,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 5,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 17,
      },
    ],
  },

  // April 8, 2025 - Multiple time slots
  {
    trainNumber: "LI3-1",
    route: "Lagos - Ibadan",
    timeOfDay: "Morning Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "10:03",
      date: "08 - Apr - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "11:45",
      date: "08 - Apr - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 12,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 20,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 5,
      },
    ],
  },
  {
    trainNumber: "LI3-2",
    route: "Lagos - Ibadan",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "13:03",
      date: "08 - Apr - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "14:45",
      date: "08 - Apr - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 5,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 16,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 9,
      },
    ],
  },
  {
    trainNumber: "LI3-3",
    route: "Lagos - Ibadan",
    timeOfDay: "Evening Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "15:30",
      date: "08 - Apr - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "17:15",
      date: "08 - Apr - 2025",
    },
    duration: "1 hr, 45 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 21,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 9,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 8,
      },
    ],
  },

  // April 20, 2025 - Multiple time slots
  {
    trainNumber: "LI3-4",
    route: "Lagos - Ibadan",
    timeOfDay: "Morning Train",
    departure: {
      station: "Babatunde Raji Fashola Station",
      street: "Agege",
      year: "2025",
      time: "10:03",
      date: "20 - Apr - 2025",
    },
    arrival: {
      station: "Lateef Kayode Jakande Station",
      street: "Agbado",
      year: "2025",
      time: "11:45",
      date: "20 - Apr - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 25,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 10,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 6,
      },
    ],
  },
  {
    trainNumber: "LI3-5",
    route: "Lagos - Ibadan",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Babatunde Raji Fashola Station",
      street: "Agege",
      year: "2025",
      time: "13:03",
      date: "20 - Apr - 2025",
    },
    arrival: {
      station: "Lateef Kayode Jakande Station",
      street: "Agbado",
      year: "2025",
      time: "14:45",
      date: "20 - Apr - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 13,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 19,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 8,
      },
    ],
  },

  // May 7, 2025 - Multiple time slots
  {
    trainNumber: "LI4-1",
    route: "Lagos - Ibadan",
    timeOfDay: "Morning Train",
    departure: {
      station: "Professor Yemi Osinbajo Station",
      street: "Kajola",
      year: "2025",
      time: "07:03",
      date: "07 - May - 2025",
    },
    arrival: {
      station: "Olu Fumilayo Ransome Kuti Station",
      street: "Papalanto",
      year: "2025",
      time: "08:45",
      date: "07 - May - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 14,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 20,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 5,
      },
    ],
  },
  {
    trainNumber: "LI4-2",
    route: "Lagos - Ibadan",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Professor Yemi Osinbajo Station",
      street: "Kajola",
      year: "2025",
      time: "13:03",
      date: "07 - May - 2025",
    },
    arrival: {
      station: "Olu Fumilayo Ransome Kuti Station",
      street: "Papalanto",
      year: "2025",
      time: "14:45",
      date: "07 - May - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 8,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 14,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 11,
      },
    ],
  },
  {
    trainNumber: "LI4-3",
    route: "Lagos - Ibadan",
    timeOfDay: "Evening Train",
    departure: {
      station: "Professor Yemi Osinbajo Station",
      street: "Kajola",
      year: "2025",
      time: "16:03",
      date: "07 - May - 2025",
    },
    arrival: {
      station: "Olu Fumilayo Ransome Kuti Station",
      street: "Papalanto",
      year: "2025",
      time: "17:45",
      date: "07 - May - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 21,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 9,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 8,
      },
    ],
  },

  // May 18, 2025 - Multiple time slots
  {
    trainNumber: "LI4-4",
    route: "Lagos - Ibadan",
    timeOfDay: "Morning Train",
    departure: {
      station: "Aremo Olusegun Osoba Station",
      street: "Olodo",
      year: "2025",
      time: "07:03",
      date: "18 - May - 2025",
    },
    arrival: {
      station: "Ladoke Akintola Station",
      street: "Omi-Adio",
      year: "2025",
      time: "08:45",
      date: "18 - May - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 9,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 11,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 13,
      },
    ],
  },
  {
    trainNumber: "LI4-5",
    route: "Lagos - Ibadan",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Aremo Olusegun Osoba Station",
      street: "Olodo",
      year: "2025",
      time: "13:03",
      date: "18 - May - 2025",
    },
    arrival: {
      station: "Ladoke Akintola Station",
      street: "Omi-Adio",
      year: "2025",
      time: "14:45",
      date: "18 - May - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 17,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 8,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 10,
      },
    ],
  },

  // June 6, 2025 - Multiple time slots
  {
    trainNumber: "LI5-1",
    route: "Lagos - Ibadan",
    timeOfDay: "Morning Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "13:03",
      date: "06 - Jun - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "14:45",
      date: "06 - Jun - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 7,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 12,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 15,
      },
    ],
  },
  {
    trainNumber: "LI5-2",
    route: "Lagos - Ibadan",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "16:03",
      date: "06 - Jun - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "17:45",
      date: "06 - Jun - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 5,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 16,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 9,
      },
    ],
  },
  {
    trainNumber: "LI5-3",
    route: "Lagos - Ibadan",
    timeOfDay: "Evening Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "19:30",
      date: "06 - Jun - 2025",
    },
    arrival: {
      station: "Professor Wole Soyinka Station",
      street: "Abeokuta",
      year: "2025",
      time: "21:15",
      date: "06 - Jun - 2025",
    },
    duration: "1 hr, 45 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 21,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 9,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 8,
      },
    ],
  },

  // June 29, 2025 - Multiple time slots
  {
    trainNumber: "LI5-4",
    route: "Lagos - Ibadan",
    timeOfDay: "Morning Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "07:03",
      date: "29 - Jun - 2025",
    },
    arrival: {
      station: "Obafemi Awolowo Station",
      street: "Moniya",
      year: "2025",
      time: "08:45",
      date: "29 - Jun - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 20,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 10,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 8,
      },
    ],
  },
  {
    trainNumber: "LI5-5",
    route: "Lagos - Ibadan",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "13:03",
      date: "29 - Jun - 2025",
    },
    arrival: {
      station: "Obafemi Awolowo Station",
      street: "Moniya",
      year: "2025",
      time: "14:45",
      date: "29 - Jun - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 17,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 8,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 10,
      },
    ],
  },

  // July 2, 2025 - Multiple time slots
  {
    trainNumber: "IL6-1",
    route: "Ibadan - Lagos",
    timeOfDay: "Morning Train",
    departure: {
      station: "Obafemi Awolowo Station",
      street: "Moniya",
      year: "2025",
      time: "07:03",
      date: "02 - Jul - 2025",
    },
    arrival: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "08:45",
      date: "02 - Jul - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 18,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 6,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 10,
      },
    ],
  },
  {
    trainNumber: "IL6-2",
    route: "Ibadan - Lagos",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Obafemi Awolowo Station",
      street: "Moniya",
      year: "2025",
      time: "11:03",
      date: "02 - Jul - 2025",
    },
    arrival: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "12:45",
      date: "02 - Jul - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 6,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 9,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 14,
      },
    ],
  },
  {
    trainNumber: "IL6-3",
    route: "Ibadan - Lagos",
    timeOfDay: "Evening Train",
    departure: {
      station: "Obafemi Awolowo Station",
      street: "Moniya",
      year: "2025",
      time: "16:03",
      date: "02 - Jul - 2025",
    },
    arrival: {
      station: "Mobolaji Johnson Station",
      street: "Ebute Metta",
      year: "2025",
      time: "17:45",
      date: "02 - Jul - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 15,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 11,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 8,
      },
    ],
  },

  // July 17, 2025 - Multiple time slots
  {
    trainNumber: "IL6-4",
    route: "Ibadan - Lagos",
    timeOfDay: "Morning Train",
    departure: {
      station: "Olu Fumilayo Ransome Kuti Station",
      street: "Papalanto",
      year: "2025",
      time: "07:03",
      date: "17 - Jul - 2025",
    },
    arrival: {
      station: "Professor Yemi Osinbajo Station",
      street: "Kajola",
      year: "2025",
      time: "08:45",
      date: "17 - Jul - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 10,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 6,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 14,
      },
    ],
  },
  {
    trainNumber: "IL6-5",
    route: "Ibadan - Lagos",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Olu Fumilayo Ransome Kuti Station",
      street: "Papalanto",
      year: "2025",
      time: "13:03",
      date: "17 - Jul - 2025",
    },
    arrival: {
      station: "Professor Yemi Osinbajo Station",
      street: "Kajola",
      year: "2025",
      time: "14:45",
      date: "17 - Jul - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 20,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 10,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 8,
      },
    ],
  },

  // July 21, 2025 - Multiple time slots
  {
    trainNumber: "IL6-6",
    route: "Ibadan - Lagos",
    timeOfDay: "Morning Train",
    departure: {
      station: "Ladoke Akintola Station",
      street: "Omi-Adio",
      year: "2025",
      time: "07:03",
      date: "21 - Jul - 2025",
    },
    arrival: {
      station: "Aremo Olusegun Osoba Station",
      street: "Olodo",
      year: "2025",
      time: "08:45",
      date: "21 - Jul - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 19,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 8,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 6,
      },
    ],
  },
  {
    trainNumber: "IL6-7",
    route: "Ibadan - Lagos",
    timeOfDay: "Afternoon Train",
    departure: {
      station: "Ladoke Akintola Station",
      street: "Omi-Adio",
      year: "2025",
      time: "13:03",
      date: "21 - Jul - 2025",
    },
    arrival: {
      station: "Aremo Olusegun Osoba Station",
      street: "Olodo",
      year: "2025",
      time: "14:45",
      date: "21 - Jul - 2025",
    },
    duration: "1 hr, 42 mins",
    classes: [
      {
        type: "First Class",
        priceAdult: "₦6000",
        priceChild: "₦4500",
        totalSeats: 50,
        reserved: 14,
      },
      {
        type: "Business Class",
        priceAdult: "₦5000",
        priceChild: "₦4000",
        totalSeats: 40,
        reserved: 6,
      },
      {
        type: "Standard Class",
        priceAdult: "₦3000",
        priceChild: "₦2500",
        totalSeats: 100,
        reserved: 10,
      },
    ],
  },
];

module.exports = trainSchedules;
